name: Greeting
# on: push
on: 
    push:
        branches:
            - main
            - 'feature/**'
        paths-ignore:
            - '.github/workflows/*'  
            - README.md  
    workflow_dispatch:
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: echo "Hello world!"